home:
  path: /
  controller: App\Controller\HomeController::index

property.index:
  path: /buy
  controller: App\Controller\PropertyController::index

admin.property.index:
  path: /admin
  controller: App\Controller\Admin\AdminPropertyController::index

admin.property.edit:
  path: /admin/edit/{id}
  controller: App\Controller\Admin\AdminPropertyController::edit
  methods: GET|POST

admin.property.new:
  path: /admin/create
  controller: App\Controller\Admin\AdminPropertyController::new
  methods: GET|POST

admin.property.delete:
  path: /admin/delete/{id}
  controller: App\Controller\Admin\AdminPropertyController::delete
  methods: DELETE

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
